# Generated by Django 5.0.2 on 2026-05-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1516321318423-f06f85e504b3'),
            preserve_default=False,
        ),
    ]
